### ISSUE TITLE
promote the linux.conf.au FP miniconf

### ISSUE THREAD

**Issue by frasertweedale** [haskellweekly/haskellweekly.github.io#119]
linux.conf.au 2018 (Jan 22..26, Sydney) will feature the Real World Functional Programming
miniconf  on either Mon 22nd or Tues 23rd.

The call for papers is open until November 27th.  Full details at
https://linux.conf.au/programme/miniconfs/functional-programming/.

It would be great if you could mention the CFP in the *Call for participation* section of an upcoming issue!

**Comment by tfausak** [comment]
Thanks for the suggestion! We haven't had a call for papers before, but I think that's a great idea. It should fit nicely into the call for participation section.
