### ISSUE TITLE
End of year issue

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly.github.io#133]
Last year I did a small roundup of the most popular links at the end of the year: https://haskellweekly.news/issues/35.html

I'd like to do something similar this year. I could either do the top _N_ links of the year or the best link from each issue. Choosing the best link from each issue is easy, but it also results in a lot of links. And what happens if one issue had two killer links? On the other side of things, should the top _N_ links be chosen by absolute number of clicks or percentage clicks from subscribers? In either case, should web clicks count, or should only email clicks matter?

**Comment by tfausak** [comment]
Also, last year I compiled these stats by querying the MailChimp API with a Haskell script. If I do that again this year, I should open source it.

**Comment by alexeyzab** [comment]
IMHO, top N links of the year is a good idea. The absolute number of clicks seems fine, same with web clicks count.

**Comment by tfausak** [comment]
I created a script for pulling a bunch of information from the MailChimp API: https://gist.github.com/tfausak/cf3e843b199afac3d0ecb3d3b74207b4

**Comment by tfausak** [comment]
I updated the Gist to include the output too. 

![Total subscribers](https://gist.githubusercontent.com/tfausak/cf3e843b199afac3d0ecb3d3b74207b4/raw/57ec6cad93fc6c1d9567e1aa4c407ec5c94f99b0/output-total-subscribers.png)

![New subscribers](https://gist.githubusercontent.com/tfausak/cf3e843b199afac3d0ecb3d3b74207b4/raw/57ec6cad93fc6c1d9567e1aa4c407ec5c94f99b0/output-new-subscribers.png)

The big jump in subscribers happened between issues 55 (May 18) and 56 (May 25). I don't remember what happened then. 

![Open rate](https://gist.githubusercontent.com/tfausak/cf3e843b199afac3d0ecb3d3b74207b4/raw/57ec6cad93fc6c1d9567e1aa4c407ec5c94f99b0/output-open-rate.png)

![Click rate](https://gist.githubusercontent.com/tfausak/cf3e843b199afac3d0ecb3d3b74207b4/raw/57ec6cad93fc6c1d9567e1aa4c407ec5c94f99b0/output-click-rate.png)

These are the top 20 links:

Clicks | URL
--- | ---
223 | http://www.haskellforall.com/2017/10/advice-for-haskell-beginners.html
215 | https://bartoszmilewski.com/2017/09/06/monads-monoids-and-categories/
214 | https://www.reddit.com/r/haskell/comments/73e7l3/i_made_bartosz_milewskis_book_category_theory_for/
196 | https://codygman.github.io/posts/2017-07-30-faster-command-line-tools-with-haskell.html
175 | http://jeremymikkola.com/posts/2017_07_11_free_monad_cheatsheet.html
173 | https://haskellexists.blogspot.de/2017/02/ten-example-uses-of-monads.html
168 | https://a-tour-of-go-in-haskell.syocy.net/en_US/index.html
166 | https://deque.blog/2017/06/14/10-things-idris-improved-over-haskell/
164 | http://vaibhavsagar.com/blog/2017/08/13/i-haskell-a-git/
164 | https://tech-blog.capital-match.com/posts/3-anatomy-of-haskell-web-app.html
162 | http://argumatronic.com/posts/2017-09-27-haskell-is-useless.html
162 | https://philipnilsson.github.io/Badness10k/posts/2017-05-07-escaping-hell-with-monads.html
162 | http://tech.frontrowed.com/2017/09/22/aggregations/
155 | https://haskelltools.blogspot.hu/2017/04/announcing-haskell-tools.html
155 | https://medium.com/@djoyner/my-haskell-in-production-story-e48897ed54c
155 | https://hmemcpy.com/2017/10/becoming-foolish/
149 | https://medium.com/@sjsyrek/five-minutes-to-monoid-fe6f364d0bba
149 | https://www.reddit.com/r/haskell/comments/5wb5qw/how_do_you_guys_get_anything_done/
147 | http://events.techcast.com/bigtechday10/Garmisch-1345/

**Comment by tfausak** [comment]
This is shaping up to be a deeper dive, so I'm going to do a write up on my blog and link to it from issue 87 (#139): https://github.com/tfausak/tfausak.github.io/pull/143
