### ISSUE TITLE
Found a haskell job

### ISSUE THREAD

**Issue by locovna** [haskellweekly/haskellweekly.github.io#136]
Hello!
Not sure if it is a right place to write about something like that, but that's only way which I've found to contact you.
I've noticed, that `Jobs` section is pretty poor, so when I found a related vacancy, I feel confident to notify you about it. Unfortunately, it's in Russian, but I'm sure a few people from such location are reading haskell weekly and it could help someone to find his/her dream job, 'cause the company, in my opinion, is great: [biocad](https://biocadglobal.com)(eng)

[[RU] Haskell Developer](https://spb.hh.ru/vacancy/23792285)

**Comment by tfausak** [comment]
Thanks for the suggestion! This is definitely the right place for this. I'll be sure to include this job posting in next week's issue.

**Comment by locovna** [comment]
Oh, great! Thank you 👍
