### ISSUE TITLE
Include event locations

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly.github.io#150]
@MaxGabriel suggested that I include the locations of the upcoming events. That sounds like a good idea to me!

**Comment by tfausak** [comment]
Also, it might be worth exploring an overhaul of the events section. For example, the [Rust community calendar](https://calendar.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc@group.calendar.google.com) is excellent and much easier to browse than a bunch of links in Haskell Weekly.

**Comment by tfausak** [comment]
I included locations in issue 93 (#153). I'll be sure to continue doing that.

**Comment by MaxGabriel** [comment]
Thanks!
