### ISSUE TITLE
Collect information about featured authors

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly.github.io#152]
I think there is a valuable feature Haskell Weekly could be providing that it isn't: A list of good authors to follow who produce Haskell content. Currently there are two ways to get this information:

1. See who Haskell Weekly follows on Twitter. This isn't great because not everyone uses Twitter. Also Twitter can have a lot more noise to signal compared to a blog. https://twitter.com/haskellweekly/following

2. Trawl through issues of Haskell Weekly and add sites to a feed reader or something. (This is actually what I do right now! Ugh.)

Both ways suck. I have people ask who to follow in the Haskell community, and I wish I could point to something on Haskell Weekly to answer that. Haskell Weekly seems well situated to provide such a list. 

So I'm proposing that I collect information about authors features in Haskell Weekly. The idea is to provide the information in both a way that is good for humans as well as a machine-readable format. The end result could even be used to provide a service like [Planet Haskell](https://planet.haskell.org). 

For each author, the following information would be immediately useful:

- Name. For most authors, this is a person. Sometimes it's a company, like "FP Complete", and sometimes it's a project, like "Stackage". 

- Site/URL. This is the home page, not the specific piece of content. 

- Feed. Not everything has a feed, but if Atom or RSS is available, it would go here. I prefer Atom over RSS.

- Twitter. Also not ubiquitous. However Haskell Weekly announces new issues on Twitter and mentioning featured authors is a nice way to alert them as well as increase engagement.

**Comment by tfausak** [comment]
This may end up feeling similar to [Haskell News](https://github.com/haskellnews/haskellnews), but hopefully with a broader set of sources.

**Comment by tfausak** [comment]
I still have some work to do on the operations side of things, but:

- I wrote an application for this: https://github.com/haskellweekly/reveille
- I deployed the application to Digital Ocean: http://192.241.159.80

I'm going to add all of the authors from previous issues of Haskell Weekly, then use this for a couple weeks before releasing it for real.

**Comment by owickstrom** [comment]
@tfausak I should get the Atom feed up for Haskell at Work, then! :smiley:

**Comment by tfausak** [comment]
Fantastic, thank you! https://github.com/haskellweekly/reveille/commit/221e7f5ef4a3cefdcf0135927eeca0a78c6a26b3

**Comment by tfausak** [comment]
This is pretty much done now. I have more work to do in terms of polish, but the nuts and bolts are there.
