### ISSUE TITLE
Change how deploys work

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly.github.io#157]
The current setup is pretty crappy:

- Rendered HTML lives on the `master` branch, which nobody should ever actually look at. https://github.com/haskellweekly/haskellweekly.github.io/tree/master
- Development happens on the `hakyll` branch, which is automatically rendered and pushed to `master` on CI. Also it's poorly named because it doesn't use Hakyll anymore (since #84). https://github.com/haskellweekly/haskellweekly.github.io/tree/hakyll
- Each issue happens on its own branch, like `issue-94`, which usually gets merged into `hakyll` for publication. https://github.com/haskellweekly/haskellweekly.github.io/tree/issue-94

This is all very confusing and no doubt hampers contributions. I think a better system would be:

- Develop on the `master` branch. 
- Publish to the `gh-pages` branch.
- Use tags to control publishing rather than publishing whatever's on `master` at any given time.

**Comment by alexeyzab** [comment]
To make sure I understand: add all new content on the `master` branch, tag a finished issue, that tag gets published to the `gh-pages` branch by CI?

**Comment by tfausak** [comment]
Yup, that's the desired workflow I had in mind. That way things work more like a normal software project.

**Comment by tfausak** [comment]
Turns out that user pages (like `user.github.io`) must use the `master` branch. They can't use `gh-pages`. GitHub says:

> User pages must be built from the `master` branch.

So `master` is going to have to be the deployment branch. That's alright because something else can be set as the default/base branch. It's a little confusing, but shouldn't be too much of a problem in practice.

**Comment by tfausak** [comment]
Fixed by #161.

**Comment by tfausak** [comment]
The first new-style build worked: https://travis-ci.org/haskellweekly/haskellweekly.github.io/builds/344875365

The deploy also worked beautifully: https://github.com/haskellweekly/haskellweekly.github.io/commit/5b5d42230d660f17a9175e633ef8901fb5bd10ad

One downside to this approach is that the tags are built with no cache, so they take a bit longer.

**Comment by alexeyzab** [comment]
Awesome work!
