### ISSUE TITLE
Mood Media PureScript job ad

### ISSUE THREAD

**Issue by vladciobanu** [haskellweekly/haskellweekly.github.io#162]
We are still looking for a PureScript dev at Mood Media and was wondering if you'd mind adding it to the Jobs section for the next weekly. Here's some more details:

> Mood Media is still looking for a junior/mid-level PureScript developer to work on our Digital Signage 
 solution. PureScript experience is not required (any FP experience will do).
> The job is in Bucharest, Romania (no remote).
> We are doing all new development in PS, and migrating existing (TypeScript/Angular) code to PS as well. There are plans to migrate server-side tools and code (from C#) to Haskell.
> For more info, https://www.linkedin.com/jobs/cap/view/558610746/

Thank you

**Comment by tfausak** [comment]
I wouldn't mind at all! I'll be sure to include this in this week's issue.

**Comment by tfausak** [comment]
Thanks for the suggestion! Your job posting is in [issue 96](https://haskellweekly.news/issues/96.html).
