### ISSUE TITLE
Event: Auckland FP Meetup - 27 March - Learn FP

### ISSUE THREAD

**Issue by vertexcite** [haskellweekly/haskellweekly.github.io#163]
Please add this event to the next issue:
```
-   March 27: [Auckland FP Meetup: Learn FP Hands-on](https://www.meetup.com/Functional-Programming-Auckland/events/248322238/) in Auckland, New Zealand
```
i.e.
-   March 27: [Auckland FP Meetup: Learn FP Hands-on](https://www.meetup.com/Functional-Programming-Auckland/events/248322238/) in Auckland, New Zealand

**Comment by tfausak** [comment]
Fixed by 71d747b438c875d4265e3b9f088f6c60d447aeac.
