### ISSUE TITLE
CfP: Workshop on Functional High-Performance Computing 2018 at ICFP

### ISSUE THREAD

**Issue by keidavis** [haskellweekly/haskellweekly.github.io#169]
Hello,

I'd like to draw attention to the following--thanks for considering!

Kei Davis (as co-chair)

CALL FOR PAPERS
FHPC 2018
7th ACM SIGPLAN Workshop on Functional High-Performance Computing
September 29, 2018, St. Louis, Missouri, USA
https://icfp18.sigplan.org/track/FHPC-2018-papers

**Comment by tfausak** [comment]
Thanks for bringing this to my attention! Are you hoping to feature the call for papers, the workshop itself, or both?

**Comment by keidavis** [comment]
Thanks for your reply!

The call for papers (for the workshop--it's like a mini-conference, refereed with published proceedings) is what we'd like to advertise--thanks!

Kei
