### ISSUE TITLE
Building Blocks

### ISSUE THREAD

**Issue by icidasset** [haskellweekly/haskellweekly.github.io#172]
Hey Taylor,

Thanks for doing this newsletter, loving the content!
I was wondering if any of my work could be interesting to people?

- [Building Blocks article](https://icidasset.com/writings/building-blocks/), article.
   > A more visual approach to introducing FP and purity/immutability.
- [Shikensu](https://github.com/icidasset/shikensu), library.
   > Run a sequence of functions on in-memory representations of files.

If not, carry on.

✌️

**Comment by tfausak** [comment]
Sorry, these should've made it into issue 99. I'll be sure to include them in issue 100. Thanks for suggesting them!

**Comment by icidasset** [comment]
Thank you for including them! ✌️
