### ISSUE TITLE
Anduril Industries Job Posting

### ISSUE THREAD

**Issue by TravisWhitaker** [haskellweekly/haskellweekly.github.io#175]
Hi! I was wondering if you'd graciously consider including [Anduril Industries](https://www.anduril.com) in the jobs section of issue 102? We've reached out in a few other places and have been using roughly this blurb:

> Anduril Industries (https://www.anduril.com) is hiring. TL;DR: Come write Haskell, Rust, and Nix (and some C++ when necessary) to make autonomous robots and drones go!
>
>We're a team of software and hardware engineers from various backgrounds (game development, computer graphics, financial technology, government intelligence, biotechnology) working to improve the state of defense technology. Our strategy involves focusing on product development instead of traditional governmental processes. By funding product development ourselves instead of relying on government funds, we're able to create more focused products faster and with significantly fewer resources. By leveraging hardware and techniques that have only recently become feasible to deploy at scale (e.g. GPGPU computing), we can significantly advance the state of the defense technology market.
>
>We're searching for generally competent, mathematically inclined software engineers, and we're especially interested in those with experience in computer vision (first principles techniques and machine learning), sensor fusion, detection and tracking, and statistical parameter estimation. Our team is increasingly applying functional programming and related technologies; we run Haskell and Rust code in production and use Nix to achieve reproducible build environments and keep deployment, CI, and cross-compilation sane.
>
>If you like FP, interfacing with hardware, and solving problems in detection, tracking, and autonomous vehicle control (land and air), drop me a line at travis-at-anduril-dot-com.

Thanks so much!

**Comment by tfausak** [comment]
Thanks for the suggestion! I'd be happy to include your job posting. The blurb associated with a job posting is normally pretty short; see [issue 100](https://haskellweekly.news/issues/100.html) for some examples. If you want to shorten it yourself that would be great, otherwise I'll trim it down myself.

**Comment by TravisWhitaker** [comment]
Thanks so much! Does #176 look ok?

**Comment by tfausak** [comment]
:+1:
