### ISSUE TITLE
2nd CfP Workshop on Functional High-Performance Computing 2018

### ISSUE THREAD

**Issue by keidavis** [haskellweekly/haskellweekly.github.io#186]
https://icfp18.sigplan.org/manageCalls/FHPC-2018-papers

The 7th ACM SIGPLAN Workshop on Functional High-Performance Computing (FHPC 2018) is being held as in previous years in conjunction with the International Conference on Functional Programming (ICFP 2018) together with numerous other workshops/symposia, and as a first, colocated with Strange Loop, in St. Louis, MO, USA.

**Comment by tfausak** [comment]
Just letting you know that this didn't make it into issue 108. If you'd like to make it into issue 109, please clarify what the expected behavior of the link should be. Otherwise I'll close this after issue 109 goes out.
