### ISSUE TITLE
Building Forum Software

### ISSUE THREAD

**Issue by ibnuda** [haskellweekly/haskellweekly.github.io#187]
Mr. Fausak,

As I've promised you on [this](https://gitlab.com/ibnuda/ibnuda.gitlab.io/issues/2#note_70091313) issue, I've completed a blog post about building software.

The article in question can be reached [here](https://siskam.link/2018-04-14-cloning-fluxbb.html).

Regards,
Ibnu.

**Comment by tfausak** [comment]
Great, thanks!
