### ISSUE TITLE
Feature "Transity"

### ISSUE THREAD

**Issue by ad-si** [haskellweekly/haskellweekly.github.io#192]
Two weeks ago I published Transity (https://www.feram.io/blog/2018-06-05_transity_the_future_of_plain_text_accounting/) and I was blown away by all the feedback. So I thought it might also be interesting for the Haskell Weekly crowd.

However, it's written in PureScript.
Do you feature PureScript Projects in the newsletter as well?

**Comment by tfausak** [comment]
Looks cool! I'm not opposed to Haskell-adjacent content like PureScript and Elm. I'll be sure to add a link to your blog post in the upcoming issue. Thanks!

**Comment by ad-si** [comment]
Cool, thanks!
