### ISSUE TITLE
Feature blog post about build tools

### ISSUE THREAD

**Issue by ChShersh** [haskellweekly/haskellweekly.github.io#199]
On Reddit:

* https://www.reddit.com/r/haskell/comments/8sswa8/blog_post_build_tools_tutorial/

Or directly from website:

* https://kowainik.github.io/posts/2018-06-21-haskell-build-tools.html

**Comment by tfausak** [comment]
That post wasn't featured, but it was included in [issue 113](https://github.com/haskellweekly/haskellweekly.github.io/blob/7f8c25ccd1c84d6b47e0c8d5edb39dfb1e12bf7d/content/issues/113.markdown#in-brief).

**Comment by ChShersh** [comment]
@tfausak Sorry, my fault! Didn't notice it. That works fine to me :+1:
