### ISSUE TITLE
Call for participation: codec-beam codegen

### ISSUE THREAD

**Issue by hkgumbs** [haskellweekly/haskellweekly.github.io#205]
Hello! First, thanks for the great work in publishing this newsletter.

I have what I believe to be an interesting sub-project within my Haskell library for generating BEAM (Erlang VM bytecode). I've described the goals in detail [on this issue](https://github.com/hkgumbs/codec-beam/issues/48). I can provide more details here if that would be helpful in getting more people involved.

**Comment by tfausak** [comment]
Thanks for the suggestion! @alexeyzab will probably want to take a look at this.

**Comment by alexeyzab** [comment]
Woops, looks like I am a bit late here. Thanks for adding it, @tfausak!
