### ISSUE TITLE
Rethink events section

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly.github.io#207]
Events have extremely bad engagement. For example, this is MailChimp's link overlay from issue 117:

<img width="395" alt="screen shot 2018-08-01 at 10 09 01 pm" src="https://user-images.githubusercontent.com/408753/43558456-9715728e-95d7-11e8-8d3d-07dc9da03a55.png">

This makes sense to me: If someone is looking for a Haskell event to go to, their not going to search through Haskell Weekly for it. If someone isn't aware of a Haskell event in their area, it's unlikely that they'll make the connection thanks to Haskell Weekly.

I like that events give a sense of the overall Haskell community, but I'm not interested in continuing to spend the time on such a low impact section. (At least not in their current form; see #179.) If someone else is interested in taking over the section, I would support that. Otherwise I will remove it.

**Comment by Carloon** [comment]
I like seeing what goes on around the world. But I don't really use it. I can't volunteer to maintain it.

**Comment by chreekat** [comment]
Well, I'm only going to click on events near me. I expect others to do likewise. At the same time, I carefully *scan* the list every time, hoping to see something near me, or something that seems worth traveling for.

What are you optimizing for, exactly? :)

**Comment by chreekat** [comment]
To make my main point, I actually prefer getting info about events through Weekly for the same reason I like getting Weekly: I don't have to go trolling the web for news. I appreciate it either way!

**Comment by supermario** [comment]
Same as @chreekat here – I like scanning through the events, it's newsworthy to me that they are happening even if they're too far to attend. And sometimes – they're not!

**Comment by manuel-uberti** [comment]
Same as @chreekat  and @supermario. I find the Events section useful and I'm always reading it to find if there is an event I could go to.

**Comment by manuel-uberti** [comment]
The Meetup API sounds like a reasonable solution to me.

**Comment by tfausak** [comment]
I wrote a script for querying this information and returning it in the format that I use for Haskell Weekly. I've got to say, I like the results! It shows more events and includes more information about each event. Plus only one or two of the events would need to be pruned. 

I think this is a good solution and I'll try it out for the upcoming issue. Thanks for your feedback so far!

**Comment by tfausak** [comment]
Oops, I meant to link to the script and its output: https://gist.github.com/tfausak/c275143017f8ab4999a4f36ea82cfce6

**Comment by chreekat** [comment]
Oh yeah, that looks great!

**Comment by manuel-uberti** [comment]
Fantastic indeed

**Comment by ad-si** [comment]
@tfausak Can you maybe change the formatting and show the location first, because if the location isn't relevant I don't need to read the rest. Also maybe a table layout would be more suited!?

**Comment by tfausak** [comment]
I am definitely in favor of changing the formatting to make it easier to read. However I think that a table would be too cramped given the available space and amount of information. For example:

Date | Location | Meetup | Group
--- | --- | --- | ---
Thursday, August 9 | [Raleigh, NC, USA](https://www.openstreetmap.org/?mlat=35.77825927734375&mlon=-78.63912963867188) | [Raleigh Haskell Meetup](https://www.meetup.com/Raleigh-Haskell-Meetup/) | [(hack . yack)](https://www.meetup.com/Raleigh-Haskell-Meetup/events/253466952/)
Thursday, August 9 | [Las Vegas, NV, USA](https://www.openstreetmap.org/?mlat=36.0655517578125&mlon=-115.1436538696289) | [Las Vegas Functional Programming User Group](https://www.meetup.com/las-vegas-functional-programming/) | [Functional Programming Meetup](https://www.meetup.com/las-vegas-functional-programming/events/253192401/)
Thursday, August 9 | [Madison, WI](https://www.openstreetmap.org/?mlat=43.029998779296875&mlon=-89.5) | [Madhackers](https://www.meetup.com/madhackers/) | [hack night](https://www.meetup.com/madhackers/events/253345754/)

It's not the worst thing in the world here on GitHub, but many people read Haskell Weekly on a mobile device. How about something like this?

- Thursday, August 9 in [Raleigh, NC, USA](https://www.openstreetmap.org/?mlat=35.77825927734375&mlon=-78.63912963867188): [(hack . yack)](https://www.meetup.com/Raleigh-Haskell-Meetup/events/253466952/) by [Raleigh Haskell Meetup](https://www.meetup.com/Raleigh-Haskell-Meetup/)
- Thursday, August 9 in [Las Vegas, NV, USA](https://www.openstreetmap.org/?mlat=36.0655517578125&mlon=-115.1436538696289): [Functional Programming Meetup](https://www.meetup.com/las-vegas-functional-programming/events/253192401/) by [Las Vegas Functional Programming User Group](https://www.meetup.com/las-vegas-functional-programming/)
- Thursday, August 9 in [Madison, WI](https://www.openstreetmap.org/?mlat=43.029998779296875&mlon=-89.5): [hack night](https://www.meetup.com/madhackers/events/253345754/) by [Madhackers](https://www.meetup.com/madhackers/)

I'm not crazy about the high density of links because I think it makes it harder to read. So maybe that could be slimmed down too? 

- Thursday August 9 in Raleigh, NC, USA by Raleigh Haskell Meetup: [(hack . yack)](https://www.meetup.com/Raleigh-Haskell-Meetup/events/253466952/)
- Thursday August 9 in Las Vegas, NV, USA by Las Vegas Functional Programming User Group: [Functional Programming Meetup](https://www.meetup.com/las-vegas-functional-programming/events/253192401/)
- Thursday August 9 in Madison, WI by Madhackers: [hack night](https://www.meetup.com/madhackers/events/253345754/)

🤷‍♂️

**Comment by manuel-uberti** [comment]
Less link is better. Also, I agree with the location as one of the first thing of every entry. :blush:

**Comment by ad-si** [comment]
Haha, I received the notification mail on my smartphone and the table looked pretty good 😅.
Mobile devices tend to be quite large nowadays 😉.

If that's a no-go for you the less linky version looks good as well.
However you should reverse the order of the location. E.g. "USA, NC, Raleigh" instead of "Raleigh, NC, USA". Makes it easier to visually parse.

Also I'd be in favor of a more numerical date format. E.g. "2018-08-09, Thu".
Feels much easier to read, but maybe that's just me because I'm so used to the format as I use it everywhere. This would also ensure that the date section always has the same length and so it would be easier to parse the locations, as they would always be at the same position as well.

**Comment by chreekat** [comment]
I could bikeshed on date and location format as well, but I'll restrain myself. :) @tfausak your last example, with one link per event, is pretty good.

**Comment by tfausak** [comment]
[Issue 120](https://haskellweekly.news/issues/120.html) went out with short event descriptions and only one link per event. I'm pretty happy with how it turned out, but I'm also willing to keep iterating on the design. What do y'all think?

**Comment by manuel-uberti** [comment]
The events section with the date and the location in front is much clearer now.

**Comment by tfausak** [comment]
Thanks for the feedback, y'all! I'm going to close this now, but please feel free to open an issue if you think the events (or anything else) in Haskell Weekly can be better!
