### ISSUE TITLE
Call for Participation: Pure-C: A C backend for PureScript

### ISSUE THREAD

**Issue by felixSchl** [haskellweekly/haskellweekly.github.io#212]
Hi, thanks for maintaining this fantastic newsletter. I've been building up a project over the last few weeks to compile PureScript code to C and was wondering if it would be suitable for the newsletter as I do see PureScript related content come through from time to time.

More details and links are provided on this announcement post.

https://medium.com/@felixschlitter/announcing-pure-c-a-c-backend-for-purescript-c6bc05562fde

My goal is to raise awareness and hopefully find contributors so the project can grow legs.

**Comment by alexeyzab** [comment]
@felixSchl Hey there! Is there a particular issue you'd like to be featured in the CFP section? I am leaning towards https://github.com/pure-c/pure-c/issues/23 so far.

**Comment by alexeyzab** [comment]
Sounds good, I'll include https://github.com/pure-c/pure-c/issues/10 for starters then, thanks!

**Comment by felixSchl** [comment]
Thanks heaps!

**Comment by alexeyzab** [comment]
Closed in  fc89d18
