### ISSUE TITLE
PureScript jobs available at CitizenNet

### ISSUE THREAD

**Issue by thomashoneyman** [haskellweekly/haskellweekly.github.io#215]
Hi folks! We have PureScript engineering positions open at CitizenNet, and I'd love to have them as a part of the Haskell Weekly newsletter. Granted, PureScript isn't Haskell, so perhaps it's not the right fit, but I thought Haskell engineers might still have interest in these sorts of positions.

https://angel.co/citizennet/jobs/437899-front-end-fullstack-developer-purescript

Let me know if this would be a good fit, and if so, I can provide a description of the right sort of length to fit the newsletter.

Thanks!

**Comment by tfausak** [comment]
Sounds good to me! PureScript is close enough to Haskell that I feel okay including PureScript content in Haskell Weekly.

**Comment by thomashoneyman** [comment]
Great! Is there a certain character limit or word count to a posting that you'd suggest? A couple sentences OK?

**Comment by tfausak** [comment]
I normally shoot for about 4 lines of text, which comes out to around 300 characters or so. A couple sentences should be fine.

**Comment by thomashoneyman** [comment]
How's something like this sound?

> CitizenNet is hiring PureScript engineers! Come work at the leading social advertising platform in entertainment, now a key part of Condè Nast's _Spire_ data team managing one of the world's largest content networks. Contribute to open source, build polished interfaces in PureScript, and work with talented & friendly teammates in Los Angeles.

**Comment by thomashoneyman** [comment]
Thanks!
