### ISSUE TITLE
Please add the author to the article

### ISSUE THREAD

**Issue by adomokos** [haskellweekly/haskellweekly.github.io#219]
Thank you for publishing `Haskell Weekly`! It's a great resource.

However, whenever I receive it, I always miss the authors from the listed articles.
Check out what [Ruby Weekly](https://haskellweekly.news/issues/129.html) has. Do you think we could have something similar in the future?

Thanks.

I include an image with my highlights from `Ruby Weekly`:

![add-author-name](https://user-images.githubusercontent.com/80530/47313839-9f43c780-d605-11e8-9444-44f6b61b5ca1.png)

**Comment by tfausak** [comment]
Thanks for the suggestion! That's a great idea. I'll be sure to include authors in future issues. 

In fact, I already collect authorship information. If you're interested in authors from previous issues, check this out: <https://airtable.com/shrPtsG8SLq5swdsM>.

**Comment by tfausak** [comment]
Ah, crap! I forgot to do this for today's issue. I'm going to reopen this so I don't forget next week.

**Comment by adomokos** [comment]
Yeah, I look and was a bit puzzled by it. Thank you!
