### ISSUE TITLE
Paper "Exceptionally Monadic Error Handling"

### ISSUE THREAD

**Issue by rybak** [haskellweekly/haskellweekly.github.io#223]
Suggesting for the next issue. [Paper "Exceptionally Monadic Error Handling. Looking at bind and squinting really hard"](https://arxiv.org/pdf/1810.13430.pdf) by @oxij is quite an interesting read. It has been published on arxiv.org on 2018-10-31.

The paper presents new approach for error-handling using a `Monad a e` type indexed twice. First by element type `a` as a regular `Monad`, and second — by the error type `e`.

Quote from "Extended Abstract" of the paper:

>     class ConjoinedMonads c where
>       return :: a -> c e a
>       (>>=) :: c e a -> (a -> c e b) -> c e b
>       throw :: e -> c e a
>       catch :: c e a -> (a -> c e' a) -> c e' a

**Comment by tfausak** [comment]
Looks good to me! I would accept a PR adding a featured link to this content, although I would prefer linking to the abstract rather than the PDF directly: <https://arxiv.org/abs/1810.13430>. I would also be happy to add this content myself if you'd prefer that. Thanks!
