### ISSUE TITLE
A study mapping Software Design Patterns to Haskell type classes

### ISSUE THREAD

**Issue by thma** [haskellweekly/haskellweekly.github.io#224]
Suggestion for one of your next issues:
Inspired by the Typeclassopedia I started to study how software designs patterns relate to concepts of functional programming and the Haskell type classes in particular.
This research resulted is a longer essay with several code examples in Haskell.

Here is the link:
https://github.com/thma/LtuPatternFactory

**Comment by tfausak** [comment]
Nice! I'd be happy to accept a PR adding a featured link to this content. Or I can add it myself if you'd prefer that. Thanks!

**Comment by thma** [comment]
I'd prefer to have the PR done by you, as I'm not yet familiar with your way of doing these things.
For the editorial text of the featured link I think you could quote (or rephrase) from the introduction section https://github.com/thma/LtuPatternFactory#lambda-the-ultimate-pattern-factory.
thanks,
Thoms
