### ISSUE TITLE
Hakyll Pt. 1 – Setup & Initial Customization

### ISSUE THREAD

**Issue by rpearce** [haskellweekly/haskellweekly.github.io#225]
Hello!

I'm doing an introductory series to hakyll, and this is the first:
https://robertwpearce.com/hakyll-pt-1-setup-and-initial-customization.html

If this is desired, I'm happy to open a PR once issue `132.markdown` is initially created? I'm not sure what the etiquette is around that.

Thanks,
Robert

**Comment by tfausak** [comment]
Looks great! I started issue 132. Usually I do it quicker, but I've been traveling the past few days. I'd be happy to accept a PR adding a featured link to your post. Thanks!

**Comment by rpearce** [comment]
Cool! I'll make it happen right now
