### ISSUE TITLE
Hakyll Pt. 2 – Generating a Sitemap XML File

### ISSUE THREAD

**Issue by rpearce** [haskellweekly/haskellweekly.github.io#229]
Hello again!

I'm doing an introductory series to hakyll, and this is the second post:
https://robertwpearce.com/hakyll-pt-2-generating-a-sitemap-xml-file.html

If this is desired, I'm happy to open a PR once issue `134.markdown` is created!

Thanks,
Robert

**Comment by tfausak** [comment]
Thanks for the suggestion! Sorry I didn't get around to starting issue 134 earlier this week. I went ahead and featured your post in the upcoming issue. It'll be published tomorrow!
