### ISSUE TITLE
Meetup in Phoenix AZ USA

### ISSUE THREAD

**Issue by gregberns** [haskellweekly/haskellweekly.github.io#230]
We've been running an FP meetup for 3 years in Phoenix, Arizona, USA, mainly aimed at typed FP. Would be great if you could include it in the newsletter. It runs the first Tuesday of every month.

https://www.meetup.com/Functional-First-Phoenix/

Thanks by the way, there have been some really great articles the last couple months. The Go/Haskell/OCaml article was a fav of mine.

**Comment by tfausak** [comment]
Thanks for the heads up! The event section is mostly automated these days. Essentially as long as the meetup or group has the word "Haskell" somewhere in it (title or description), it should be found. I've manually added your next meetup (on December 4) to the upcoming issue.
