### ISSUE TITLE
Functional programming conference f(by) 2019 in Minsk on January 26, 2019

### ISSUE THREAD

**Issue by Artsiomenka** [haskellweekly/haskellweekly.github.io#241]
Hi, could you please share information about our 5th annual F(by) conference on Jan 26 in Minsk.

Sample text could be:
If you are in Eastern Europe do not miss 5th annual F(by) conference on Jan 26 in Minsk https://fby.by/. This year Haskell talks are given by Vitaly Bragilevskyi @VBragilevsky, Christoph Hegemann @Kritzcreek (PureScript & Haskell), Andrey Lelechenko @Bodigrim. In addition the keynote by Venkat Subramaniam, and many other FP talks. Belarus is visa free for 87 countries. If you cannot make it to Belarus, submit your email to get videos, which are free.

More details:
f(by) 2019 https://fby.by –  the 5th edition of the conference on functional programming in Minsk, Belarus.

For the first time f(by) will be a 2-days event:

    January 25 - Scala Night
    January 26 - Main Conference Day

The main conference day

On January 26th we will have 2 tracks of talks on different functional programming languages:

    Practical talks: success stories of FP languages usage;
    Theoretical talks: programming language theory, mathematics, programming for the sake of programming, new things in FP languages.

Among the speakers:

    Venkat Subramaniam @venkat_s
    Christoph Hegemann @kritzcreek
    Renzo Borgatti @reborg
    Vagif Abilov @ooobject
    Antonio Monteiro @_anmonteiro
    and many more (see the website https://fby.by)

Scala Night

On the evening of January 25th we'll have a pre-event – Scala Night – with talks on Scala only. Start – 18:00. Place – SPACE (same as the conference).

    Among the speakers:
    Harmeet Singh @singh_harmeet13
    Vladimir Pavkin @vlpavkin
    Jakub Kozlowski @kubukoz

Tickets:

    Scala Night + f(by) conference = 249 BYN;
    f(by) conference pass = 199 BYN.

Organised by SPACE Production in cooperation with local FunсBY community.

**Comment by Bodigrim** [comment]
@Artsiomenka the preferred informal spelling is Andrew Lelechenko, not Andrey.
