### ISSUE TITLE
A way to feature upcoming big events

### ISSUE THREAD

**Issue by NorfairKing** [haskellweekly/haskellweekly.github.io#262]

**Comment by tfausak** [comment]
Thanks for opening this issue! I know we talked about this out of band, so I'll try to provide some context here.

Often there are "big" events coming up like conferences. It would be nice to include them, but the "events" section in Haskell Weekly is typically focused on the upcoming week. I would like to figure out a way to include events that are a long time away, potentially up to a year.

**Comment by tfausak** [comment]
Here's a list of previous events that may fall into this category:

- #267: ICFP 2019
- #265: FPure
- #256: LambdAle
- #255: FP Days 2019
- #241: f(by) 2019

And probably many others. See also this relevant discussion on Twitter: https://twitter.com/qrilka/status/1139252604695961600
