### ISSUE TITLE
Make dates easier to parse visually

### ISSUE THREAD

**Issue by HeinrichApfelmus** [haskellweekly/haskellweekly.github.io#264]
The dates would become easier to parse for a human if they were presented in a calendar-like / tabular format. I'm thinking of something like this (from Issue 153):

<table>
  <thead>
    <th>Thu, March 28
    <th>Fr, March 29
    <th>Sa, March 30
    <th>Su, March 31
    <th>Mo, April 1
    <th>Tu, April 2
    <th>We, April 3
  <tr>
    <td>Chicago, IL, USA
      <br> by The Project Euler Sprint:
      <br><a href="https://www.meetup.com/Project-Euler-Sprint/events/ngwzxmyzfblc/">Project Euler Sprint</a>
    <td>
    <td>Boston, MA, USA
    <br>by Weekly Functional Programming Meetup:
    <br><a href="https://www.meetup.com/Weekly-Functional-Programming-Meetup/events/vmhptqyzfbnc/">Hang out + short talk (title not yet announced)</a>
    <td>
    <td> Irvine, CA
    <br> by Orange Combinator — Functional Programming In OC:
    <br><a href="https://www.meetup.com/orange-combinator/events/lxvjrpyzgbcb/">Combinating - The Weekly Function</a>
    <td>
    <td>
  <tr>
    <td>
    <td>
    <td>Berkeley, CA
      <br>by Code Self Study: 
      <br><a href="https://www.meetup.com/codeselfstudy/events/dkwpzpyzfbnc/">Open Programming Session (Saturday Afternoon)</a>
    <td>
    <td>
    <td>
    <td>
</table>

Of course, the layout would need to be improved, and it is not clear how well this carries over to non-HTML formats. Perhaps a preprocessing step that parses the current format and renders it in table form for HTML output? Perhaps with a JavaScript button that allows to switch between views?

**Comment by tfausak** [comment]
I'm alright with changing up how events are displayed. This has come up before (#207). I think things are better now, but they can always be even better! 

One reason I've shied away from tables so far is that they have a tendency to bunch up the text and cause a bunch of weird line breaks.
