### ISSUE TITLE
post about Rubik's Cubes & Algebra & Haskell

### ISSUE THREAD

**Issue by JaredCorduan** [haskellweekly/haskellweekly.github.io#266]
I wrote a post about the algebra of the Rubik's Cube and how I implemented it in Haskell.

link: https://jaredcorduan.github.io/posts/2019-04-10--rubik-group.html

quick description: "The Rubik's Cube has a nice algebraic description. This post explains the algebra and how I implemented it in Haskell."

**Comment by tfausak** [comment]
Thanks for the suggestion! I'll feature your post in the upcoming issue.

**Comment by JaredCorduan** [comment]
great, thanks! :smile:
