### ISSUE TITLE
FunctorOf blog post

### ISSUE THREAD

**Issue by vladciobanu** [haskellweekly/haskellweekly.github.io#270]
Hello!

I wrote a blog post about a more general Functor class: FunctorOf
Url: https://cvlad.info/functor-of/
Twitter: https://twitter.com/cvlad

Thanks!

**Comment by tfausak** [comment]
Thanks for the suggestion! I added your post in b8f266dff25d0e87479871f86d52cdb8e7205502 and I'll be sure to feature it as well.
