### ISSUE TITLE
GraphQL: New maintainer

### ISSUE THREAD

**Issue by belka-ew** [haskellweekly/haskellweekly.github.io#275]
Not sure if it is worth mentioning.

Some years ago there was an unfinished [GraphQL implementation](https://hackage.haskell.org/package/graphql). The project was on hold for the last few years. Recently (officially a week ago) I took over the maintenance to continue the development. The git repository has moved: https://github.com/caraus-ecms/graphql. It is still unfinised and work-in-progress (very well usable in basic cases, though), but now under active development.

The main difference to the typical "type-safe" GraphQL alternatives is that this implementation is more low-level and more flexible.

I could probably write a blog post about my plans but I don't have big plans or promises. I'm regulary working on the library and implementing missing features step by step. Still I'm using GraphQL from Haskell in a private project, the development is mostly directed by the requirements of that project and it will remain so at least for the rest of this year.

In the last few days I was working on the pretty-printer for GraphQL queries.

**Comment by tfausak** [comment]
I'm so sorry! Somehow I didn't see this until this morning. My apologies. 

We don't typically notify about maintainer switch overs. That being said, if you write a blog post about this I'd happily include it! (It doesn't have to say much more than you've included here.)

**Comment by belka-ew** [comment]
I began to lose the hope :) No problem, thanks for the response. Then I'll prepare a blog post, but I want to write a bit more, maybe with some simple usage examples. It will take 2-3 weeks and I'll get back to you.

**Comment by tfausak** [comment]
Cool! Just open a new issue (or re open this one) when that blog post is out in the wild.

**Comment by belka-ew** [comment]
One week later than planed but here it is: https://www.caraus.io/articles/graphql-haskell-new-maintainer
