### ISSUE TITLE
Suggestion: Practical profunctor lenses & optics in PureScript

### ISSUE THREAD

**Issue by thomashoneyman** [haskellweekly/haskellweekly.github.io#276]
I've just published a thorough, practical introduction to profunctor optics in PureScript. I think it'd be interesting and useful to a Haskell audience. By the end of it a Haskeller would be comfortable writing lens code in PureScript, and it might help folks considering PureSCript on the frontend see one of its standout libraries, `profunctor-lenses`.

https://thomashoneyman.com/articles/practical-profunctor-lenses-optics

Unfortunately I missed this week's Haskell Weekly; I'll try to suggest a little earlier next time!

**Comment by tfausak** [comment]
Thanks for the suggestion! You wrote an excellent article and I'm happy to feature it in today's issue.
