### ISSUE TITLE
Add blog post about GSoC 2019 in Haskell.org from mentors perspective

### ISSUE THREAD

**Issue by chshersh** [haskellweekly/haskellweekly.github.io#277]
I think the following blog post might be a good addition to the next Haskell newsletter:

* https://kowainik.github.io/posts/gsoc2019

**Comment by tfausak** [comment]
Looks great! I’ll be sure to include it in the upcoming issue.

**Comment by tfausak** [comment]
Fixed by 0d5793ffeccf25b468c9adb36822285adcf3c5ee.
