### ISSUE TITLE
Verifying leftist heaps in Haskell

### ISSUE THREAD

**Issue by madgen** [haskellweekly/haskellweekly.github.io#278]
I wrote a blog post about verifying leftist heaps and more generally about type-level computation in Haskell. Maybe it's worth featuring in the upcoming newsletter?

**Comment by tfausak** [comment]
Sure! Do you have a link to it?

**Comment by madgen** [comment]
Sorry, I'm clearly sleep deprived.

https://dodisturb.me/posts/2019-10-03-Verifying-the-Titular-Properties-of-a-Leftist-Heap.html

**Comment by tfausak** [comment]
Fixed by 161997740c39ef7ff5e1a50683866a39e5ed416f.
