### ISSUE TITLE
Figure out a way to feature old content

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly.github.io#51]
@eborden suggested this. 

There's a lot of old content that's not news but would still be nice to feature somehow. Stuff like this:

- http://www.haskellforall.com/2016/02/state-of-haskell-ecosystem-february.html
- http://www.stephendiehl.com/posts/production.html
- https://code.facebook.com/posts/745068642270222/fighting-spam-with-haskell/
- http://comonad.com/reader/2014/letter-to-a-young-haskell-enthusiast/
- https://ocharles.org.uk/blog/pages/2014-12-01-24-days-of-ghc-extensions.html

The two problems that need solving are: 

- Where should this content go?
- How should this content be chosen?

Since I'm currently the only editor of Haskell Weekly, the news I pick reflects my bias. That's kept in check a little by only picking recent stories for each issue. If I'm reaching back to publish anything, I may have to be more careful about what I pick. 

One way around that could be to pick the "best" links from previous issues, where "best" might mean "most clicked on, according to MailChimp". Obviously that limits me to a year's worth of content at this point.

Depending on how this content is presented, how long should it last? Would it be one piece of content "from the archives" each week? Several at a time, but not on any regular schedule? What should I do if I run out of content? Do I start cycling at that point?

**Comment by eborden** [comment]
I like the idea of most clicked from mailchimp. That actually raises another interesting feature. There is existing content that predates haskellweekly, which should be represented (I think accepting bias is fine here.) and there is content you have analytics on. For known content you could display the "most clicked" from last week for anyone that hasn't caught up.

**Comment by tfausak** [comment]
I did something sort of like this at the end of 2016: https://haskellweekly.news/issues/35.html

**Comment by tfausak** [comment]
I think I'll stick to the news. I'll probably continue the "tradition" of doing a top 10 list at the end of the year.
