### ISSUE TITLE
Include link to discussion

### ISSUE THREAD

**Issue by davlse** [haskellweekly/haskellweekly.github.io#55]
It could be nice if an item also had a pointer to the relevant discussion of the link, e.g Reddit, mailing list or other relevant forum. 

Would that be interesting?

**Comment by tfausak** [comment]
I've held off doing this so far for a couple reasons:

- It's pretty easy to find the discussions. Reddit, Hacker News, and Lobsters all have search functionality. Posts to mailing lists can be found through Google. 

- There are a lot of places to discuss stuff. Should I link to Reddit? haskell-cafe? Hacker News? Planet Haskell? Lobsters? Disqus on the item itself? Lambda the Ultimate? 

In short, I think there are too many choices and they're all too easy to find.

**Comment by tfausak** [comment]
I'm going to close this for the reasons given above, but if you feel strongly about this I'm open to talk about it.
