### ISSUE TITLE
RSS feed isn't a valid link

### ISSUE THREAD

**Issue by seesolve** [haskellweekly/haskellweekly.github.io#62]
Checking the [RSS feed](https://haskellweekly.news/haskell-weekly.atom) using the [Feed Validator](http://www.feedvalidator.org) and [the feed does not validate](http://www.feedvalidator.org/check?url=https://haskellweekly.news/haskell-weekly.atom). 

Specifically, error:

`Server returned [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

The help on that error explains: 

> Your feed couldn't be validated because there was a problem downloading it from the web server. You should try to diagnose this using a web browser, and make sure that the URL you supplied resolves to an accessible file.
> 
> This usually means that the URL was wrong, or that permissions on the server don't allow us to fetch that file. The error shows the message that the server sent, which may help.

**Comment by tfausak** [comment]
Haskell Weekly uses an SSL certificate provided by [Let's Encrypt](https://letsencrypt.org). It looks like feedvalidator.org doesn't know about them. Using the W3C's feed validator we can see that the feeds are in fact valid:

- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhaskellweekly.news%2Fhaskell-weekly.atom
- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhaskellweekly.news%2Fhaskell-weekly.rss

**Comment by seesolve** [comment]
Thanks for that. Seems like I may need to do something with the RSS app I’m using.

**Comment by tfausak** [comment]
You can try using the Atom/RSS feed straight from GitHub. 

- https://raw.githubusercontent.com/haskellweekly/haskellweekly.github.io/master/haskell-weekly.atom
- https://raw.githubusercontent.com/haskellweekly/haskellweekly.github.io/master/haskell-weekly.rss

The only potential problem there is that they're served as `text/plain` rather than `application/atom+xml`.

**Comment by tfausak** [comment]
I'm going to close this. I hope those alternate feeds work for you. If not, I'm not sure what I can even do to help.
