### ISSUE TITLE
Call for Participation section

### ISSUE THREAD

**Issue by alexeyzab** [haskellweekly/haskellweekly.github.io#75]
Hi Taylor,

What do you think about adding this kind of section to the newsletter? It would include open source projects that need help, possibly including the difficulty of each issue.

This is something that This Week in Rust does and it seems to be working quite nice. Here's what that looks like:

![cfp](https://user-images.githubusercontent.com/5606260/27960768-7800d84a-62fa-11e7-8e70-bfa98eb106aa.png)

I understand that it might be a bit trickier to do this for Haskell projects, but including even a few open issues each week might be a nice way to get people more involved. Especially if there are easier issues out there, that would be a good opportunity for people new to Haskell to actually practice using it.

I am up for handling this part myself, either by encouraging people to tweet/email me with their issues and then editing the newsletter on my own or by writing up a document describing how to add new issues, where things go and so on, so that people could send the PRs here themselves.

Let me know if this is something worth doing.

Thanks!

**Comment by tfausak** [comment]
Hello again, Alexey! I think this is definitely something worth doing. Do you want to handle this section for the next issue to get a feel for how it will work?

**Comment by tfausak** [comment]
Also, looking through [the latest issue of This Week in Rust](https://this-week-in-rust.org/blog/2017/07/04/this-week-in-rust-189/), I see a few more sections Haskell Weekly may be able to co-opt:

- Updates from Rust Core: GHC doesn't move quite as fast as Rust. Also the changes are often hard to understand or relatively small. Nevertheless it might be nice to highlight changes as they happen in Trac/Phabricator rather than waiting for a release. 
- New Contributors: Seems like it would be pretty easy, but also feels like it'd put Haskell Weekly in the position of thanking people on behalf of the GHC team. 
- Approved RFCs: I'm not holding my breath for any [Haskell RFCs](https://github.com/haskell/rfcs/pulls) to be approved.
- Final Comment Period: Haskell doesn't have this process.
- New RFCs: Could be worth doing, but Haskell doesn't get that many new RFCs. 
- Style RFCs: Much to my chagrin, Haskell doesn't have a community style. Haskell Weekly could pick some tool (`hindent`, `brittany`, `stylish-haskell`) and feature something about it (new issues, PRs, releases). 
- Upcoming Events: I did this two weeks ago but didn't have enough time to do it last week. I'd like to keep doing it.
- Rust Jobs: Already talked about in #57. 
- Quote of the Week: I am personally uninterested in content like this, but I do see the appeal.

**Comment by alexeyzab** [comment]
Sure! So far I am thinking of putting it below the Package of the Week section. Should there be some limit for how old the issue is? I am thinking of starting small, maybe 3-5 issues at first. I'll try to reach out to the package maintainers to see if they could provide an estimate of how difficult a particular problem would be for someone unfamiliar with the package. I'd imagine we could follow the same [guidelines](https://users.rust-lang.org/t/twir-call-for-participation/4821) as This Week in Rust does. The main problem with keeping this on, in my opinion, is to encourage the package maintainers to adhere to the guidelines and submit their issues. Having more recent ones would be better I think. (Possibly easier to build the package, a more responsive maintainer, etc)

As for the other sections:

* Updates from GHC Core: Yeah, highlighting changes sounds like a good idea.
* New Contributors: What if we could mention the people who made their first contribution to a Haskell package here instead? Possibly to the same packages mentioned in the CFP section. Although this is probably more vague in general.
* Style RFCs: This is interesting, would that be a different tool each week or pick one and stick with it? I'd imagine people might feel strongly about their preferred style.
* Upcoming Events: This is also nice, I am up for doing this one. As far as I understand this would involve checking Meetup/Reddit/Twitter, right?
* Quote of the Week: Yeah, I feel the same way.

**Comment by tfausak** [comment]
Rust's guidelines seem good. For posterity:

> - Ensure that your project has at least one open-source licence. (we've decided to not define the term "open-source" and it is left to your own interpretation).
> - Ensure that the issue tracker for your project is publicly accessible.
> - Create a new issue in your issue tracker and clearly describe the task. Also mention the difficulty level (easy/medium/hard/tedious), either as a tag/label or somewhere in the title/description.
> - If you have specific requirements for contributors (e.g., copyright waiver), it must be mentioned in the description of the task (preferably with a link to CONTRIBUTING.md).

Aiming for 3-5 issues sounds good. I don't care how old the issues are as long as a fix is likely to be merged. 

I have struggled with community involvement in the past, but this may be a good way to get people involved. It allows people to show off their projects and encourages new people to get involved. Win-win.

---

- Updates from GHC: This is the best way to find changes to GHC that I've found: https://ghc.haskell.org/trac/ghc/timeline?ticket=on
- New contributors: First time contributors to Haskell projects in general is a huge area to search over. It might be worth doing, but it would be difficult. Maybe we could highlight first time uploaders to Hackage? 
- Style RFCs: I imagined picking one tool and sticking with it. In effect this would have Haskell Weekly pick a community style to throw its weight behind. To say that people feel strongly about their preferred style would be understating it. Check out [this thread](https://www.reddit.com/r/haskell/comments/5059gm/hindent_5_one_style_to_rule_them_all/), for example. 
- Upcoming events: I think checking Meetup should suffice. I don't often see stuff posted to Reddit or Twitter.

**Comment by alexeyzab** [comment]
I am thinking about reposting these guidelines in the issues I want to add along with an explanation about the new CFP section in Haskell Weekly. Maybe that would prompt the maintainers to watch out for the first-timers.

* Updates from GHC: Good stuff, thanks! I think I'll write up the CFP section first and then work on other things. 
* New contributors: Hm, the uploaders idea seems promising, we can try that.
* Style RFCs: Sure, sounds like a plan. Oh yeah, that's quite telling.
* Upcoming events: Gotcha!

I'll start assembling the issues today, will send a PR once it's ready.

**Comment by tfausak** [comment]
Big thanks to @alexeyzab for getting the ball rolling over at #76!

**Comment by tfausak** [comment]
Issue 63 will be the first to feature a "call for participation" section. #77
