### ISSUE TITLE
CI build is broken

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly.github.io#81]
The CI build died twice in a row:

- https://travis-ci.org/haskellweekly/haskellweekly.github.io/builds/255657701
- https://travis-ci.org/haskellweekly/haskellweekly.github.io/builds/255659376

Building simply takes too long (or consumes too much memory) for Travis to handle. I see a couple ways out of this:

- Prune the dependencies. This would be hard because Hakyll eventually depends on Pandoc, which is a beast to build.
- Switch to lighter dependencies. For example, I could get away with using [CMark](https://hackage.haskell.org/package/cmark) instead of Pandoc. This would require writing a little bit of my own code.
- Aggressively remove almost all dependencies. In other words, write my own static site generator. This might be fun but also time consuming. It could also allow me to do some interesting stuff, like representing issues as Haskell data types.
- Switch to GitHub Pages (which uses Jekyll) and avoid building anything myself. This is by far the easiest option since I'm already familiar with Jekyll. The downside is that Haskell Weekly wouldn't be built with Haskell.

**Comment by tfausak** [comment]
The latest scheduled build failed too: https://travis-ci.org/haskellweekly/haskellweekly.github.io/builds/256136633

**Comment by alexeyzab** [comment]
I wanted to see if using GHC-8.2.1 would help, but couldn't quite get `pandoc` to build. Do you think the speedup would be enough to keep the CI builds passing?

**Comment by tfausak** [comment]
It might, but some of the builds ran out of memory rather than time. Haskell Weekly doesn't need a lot of the stuff that Hakyll and Pandoc provide. Re-writing it from scratch probably wouldn't be too hard. 

In the meantime, the builds are succeeding again.

**Comment by tfausak** [comment]
Rebuilding from scratch after efe9930de214ab6151e86e7303caf8428cfae128 still timed out: https://travis-ci.org/haskellweekly/haskellweekly.github.io/builds/258141945
